# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pinkroom-api

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install all packages
        run: npm install

      - name: Build app and copy fonts
        run: |
          npm run build
          echo "Listing fonts in dist/resources/fonts"
          ls -R dist/resources/fonts

      - name: Zip artifact for deployment
        run: |
          zip -r develop.zip \
            dist \
            scripts \
            package.json \
            package-lock.json \
            node_modules \
            nest-cli.json \
            .npmrc

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: develop.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_112190D07B7545A2BAA34C3B34A74AD0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35C5ACCE15B845DB8E09934DF4A4BDD1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9DEC93427F049258A7592954DD74D16 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pinkroom-api'
          slot-name: 'develop'
          package: develop.zip

      - name: Clean previous dist on Azure (optional but recommended)
        run: |
          curl -X POST https://pinkroom-api-develop-gjf6a9a6hue4gpaj.scm.koreacentral-01.azurewebsites.net/api/command \
          -u '${{ secrets.AZURE_APP_SERVICE_DEVELOP_USER }}:${{ secrets.AZURE_APP_SERVICE_DEVELOP_PASSWORD }}' \
          -H "Content-Type: application/json" \
          -d '{"command": "rm -rf /home/site/wwwroot/dist"}'

      - name: Install dependencies on Azure
        run: |
          curl -X POST https://pinkroom-api-develop-gjf6a9a6hue4gpaj.scm.koreacentral-01.azurewebsites.net/api/command \
          -u '${{ secrets.AZURE_APP_SERVICE_DEVELOP_USER }}:${{ secrets.AZURE_APP_SERVICE_DEVELOP_PASSWORD }}' \
          -H "Content-Type: application/json" \
          -d '{"command": "npm install --production --prefix /home/site/wwwroot"}'

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: node-app
